### PR TITLE
Split the board member cards into another component

### PR DESCRIPTION
**Pull request by sohomdatta1**
Added a new component, BoardMemberCard and created a json file, board-members.json to load the board members data from.

### CODE REVIEW

**Comment by leandermaben** [comment]
Icons are currently being added to the cars
Once that is merged please modify your code to account for it

**Comment by sohomdatta1** [comment]
@leandermaben Sure will do! Also, should I add linkify the icons with dummy urls (`#`) or should that be a separate patch/PR?

**Comment by leandermaben** [comment]
You can add the the dummy urls in this PR

**Comment by leandermaben** [comment]
The icons have been added

**Comment by sohomdatta1** [comment]
@leandermaben Made the changes :) (Git merge kept messing up the div nesting which caused quite a bit of problem)

**Review by leandermaben — CHANGES_REQUESTED** [review]
Change class in line 10 to className

**Comment by leandermaben** [comment]
Would it be possible for you to squash the commits into a single one using git rebase

**Comment by sohomdatta1** [comment]
@leandermaben Made the changes and squashed everything into one commit.

**Comment by leandermaben** [comment]
Good Job!

**Pull request merged**
